# Generated by Django 3.2.20 on 2023-11-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_currency_description'),
        ('currencypost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypost',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.currency'),
        ),
    ]
