# Generated by Django 3.2.20 on 2023-11-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencypost', '0002_alter_currencypost_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencypost',
            options={'ordering': ['created_at']},
        ),
    ]
