# Generated by Django 3.2.20 on 2023-10-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-market_cap']},
        ),
    ]
