# Generated by Django 3.2.20 on 2023-10-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_currency_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
