# Generated by Django 3.2.20 on 2023-11-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20231107_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='../default_profile_y7ymw3.jpg§', upload_to='images/'),
        ),
    ]
