# Generated by Django 3.2.20 on 2023-11-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='../profile_znyvhv.jpg', upload_to='images/'),
        ),
    ]
