# Generated by Django 3.2.20 on 2023-10-18 06:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0002_alter_currency_options'),
        ('favouritecurrencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritecurrencies',
            unique_together={('user', 'currency')},
        ),
    ]
